#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteMVC.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NedvijimostDB")]
	public partial class DataModel : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdvertismentPhone(AdvertismentPhone instance);
    partial void UpdateAdvertismentPhone(AdvertismentPhone instance);
    partial void DeleteAdvertismentPhone(AdvertismentPhone instance);
    partial void InsertWebSearchFilterAdvertisment(WebSearchFilterAdvertisment instance);
    partial void UpdateWebSearchFilterAdvertisment(WebSearchFilterAdvertisment instance);
    partial void DeleteWebSearchFilterAdvertisment(WebSearchFilterAdvertisment instance);
    partial void InsertviewAdvertisment(viewAdvertisment instance);
    partial void UpdateviewAdvertisment(viewAdvertisment instance);
    partial void DeleteviewAdvertisment(viewAdvertisment instance);
    partial void InsertAdvertismentSection(AdvertismentSection instance);
    partial void UpdateAdvertismentSection(AdvertismentSection instance);
    partial void DeleteAdvertismentSection(AdvertismentSection instance);
    partial void InsertAdvertismentsPhoto(AdvertismentsPhoto instance);
    partial void UpdateAdvertismentsPhoto(AdvertismentsPhoto instance);
    partial void DeleteAdvertismentsPhoto(AdvertismentsPhoto instance);
    partial void InsertArticle(Article instance);
    partial void UpdateArticle(Article instance);
    partial void DeleteArticle(Article instance);
    partial void InsertSearchResult(SearchResult instance);
    partial void UpdateSearchResult(SearchResult instance);
    partial void DeleteSearchResult(SearchResult instance);
    partial void InsertSubPurchasePhone(SubPurchasePhone instance);
    partial void UpdateSubPurchasePhone(SubPurchasePhone instance);
    partial void DeleteSubPurchasePhone(SubPurchasePhone instance);
    partial void InsertSubPurchase(SubPurchase instance);
    partial void UpdateSubPurchase(SubPurchase instance);
    partial void DeleteSubPurchase(SubPurchase instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertAdvertisment(Advertisment instance);
    partial void UpdateAdvertisment(Advertisment instance);
    partial void DeleteAdvertisment(Advertisment instance);
    #endregion
		
		public DataModel() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NedvijimostDBConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataModel(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataModel(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataModel(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataModel(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<viewAdvertismentPhone> viewAdvertismentPhones
		{
			get
			{
				return this.GetTable<viewAdvertismentPhone>();
			}
		}
		
		public System.Data.Linq.Table<viewAdvertismentPhoto> viewAdvertismentPhotos
		{
			get
			{
				return this.GetTable<viewAdvertismentPhoto>();
			}
		}
		
		public System.Data.Linq.Table<AdvertismentPhone> AdvertismentPhones
		{
			get
			{
				return this.GetTable<AdvertismentPhone>();
			}
		}
		
		public System.Data.Linq.Table<WebSearchFilterAdvertisment> WebSearchFilterAdvertisments
		{
			get
			{
				return this.GetTable<WebSearchFilterAdvertisment>();
			}
		}
		
		public System.Data.Linq.Table<viewAdvertisment> viewAdvertisments
		{
			get
			{
				return this.GetTable<viewAdvertisment>();
			}
		}
		
		public System.Data.Linq.Table<AdvertismentSection> AdvertismentSections
		{
			get
			{
				return this.GetTable<AdvertismentSection>();
			}
		}
		
		public System.Data.Linq.Table<AdvertismentsPhoto> AdvertismentsPhotos
		{
			get
			{
				return this.GetTable<AdvertismentsPhoto>();
			}
		}
		
		public System.Data.Linq.Table<AdvertismentSubSection> AdvertismentSubSections
		{
			get
			{
				return this.GetTable<AdvertismentSubSection>();
			}
		}
		
		public System.Data.Linq.Table<Article> Articles
		{
			get
			{
				return this.GetTable<Article>();
			}
		}
		
		public System.Data.Linq.Table<SearchResult> SearchResults
		{
			get
			{
				return this.GetTable<SearchResult>();
			}
		}
		
		public System.Data.Linq.Table<SubPurchasePhone> SubPurchasePhones
		{
			get
			{
				return this.GetTable<SubPurchasePhone>();
			}
		}
		
		public System.Data.Linq.Table<SubPurchase> SubPurchases
		{
			get
			{
				return this.GetTable<SubPurchase>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<Advertisment> Advertisments
		{
			get
			{
				return this.GetTable<Advertisment>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.viewAdvertismentPhones")]
	public partial class viewAdvertismentPhone
	{
		
		private int _AdvertismentID;
		
		private string _text;
		
		private System.DateTime _createDate;
		
		private int _AdvertismentSection_Id;
		
		private string _link;
		
		private string _siteName;
		
		private bool _subpurchaseAdvertisment;
		
		private System.Nullable<System.Guid> _SubPurchase_Id;
		
		private bool _not_realestate;
		
		private bool _not_show_advertisment;
		
		private bool _isSpecial;
		
		private System.Nullable<System.DateTime> _isSpecialDateTime;
		
		private System.Nullable<int> _AdvertismentSubSection_Id;
		
		private string _phone;
		
		private int _PhoneID;
		
		public viewAdvertismentPhone()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvertismentID", DbType="Int NOT NULL")]
		public int AdvertismentID
		{
			get
			{
				return this._AdvertismentID;
			}
			set
			{
				if ((this._AdvertismentID != value))
				{
					this._AdvertismentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string text
		{
			get
			{
				return this._text;
			}
			set
			{
				if ((this._text != value))
				{
					this._text = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime NOT NULL")]
		public System.DateTime createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this._createDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvertismentSection_Id", DbType="Int NOT NULL")]
		public int AdvertismentSection_Id
		{
			get
			{
				return this._AdvertismentSection_Id;
			}
			set
			{
				if ((this._AdvertismentSection_Id != value))
				{
					this._AdvertismentSection_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this._link = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteName", DbType="VarChar(MAX)")]
		public string siteName
		{
			get
			{
				return this._siteName;
			}
			set
			{
				if ((this._siteName != value))
				{
					this._siteName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subpurchaseAdvertisment", DbType="Bit NOT NULL")]
		public bool subpurchaseAdvertisment
		{
			get
			{
				return this._subpurchaseAdvertisment;
			}
			set
			{
				if ((this._subpurchaseAdvertisment != value))
				{
					this._subpurchaseAdvertisment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubPurchase_Id", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> SubPurchase_Id
		{
			get
			{
				return this._SubPurchase_Id;
			}
			set
			{
				if ((this._SubPurchase_Id != value))
				{
					this._SubPurchase_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_not_realestate", DbType="Bit NOT NULL")]
		public bool not_realestate
		{
			get
			{
				return this._not_realestate;
			}
			set
			{
				if ((this._not_realestate != value))
				{
					this._not_realestate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_not_show_advertisment", DbType="Bit NOT NULL")]
		public bool not_show_advertisment
		{
			get
			{
				return this._not_show_advertisment;
			}
			set
			{
				if ((this._not_show_advertisment != value))
				{
					this._not_show_advertisment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isSpecial", DbType="Bit NOT NULL")]
		public bool isSpecial
		{
			get
			{
				return this._isSpecial;
			}
			set
			{
				if ((this._isSpecial != value))
				{
					this._isSpecial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isSpecialDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> isSpecialDateTime
		{
			get
			{
				return this._isSpecialDateTime;
			}
			set
			{
				if ((this._isSpecialDateTime != value))
				{
					this._isSpecialDateTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvertismentSubSection_Id", DbType="Int")]
		public System.Nullable<int> AdvertismentSubSection_Id
		{
			get
			{
				return this._AdvertismentSubSection_Id;
			}
			set
			{
				if ((this._AdvertismentSubSection_Id != value))
				{
					this._AdvertismentSubSection_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(80)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this._phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneID", DbType="Int NOT NULL")]
		public int PhoneID
		{
			get
			{
				return this._PhoneID;
			}
			set
			{
				if ((this._PhoneID != value))
				{
					this._PhoneID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.viewAdvertismentPhotos")]
	public partial class viewAdvertismentPhoto
	{
		
		private int _Id;
		
		private string _text;
		
		private System.DateTime _createDate;
		
		private string _link;
		
		private string _siteName;
		
		private bool _subpurchaseAdvertisment;
		
		private System.Nullable<System.Guid> _SubPurchase_Id;
		
		private int _PhotoId;
		
		private string _PhotoFileName;
		
		private System.Nullable<System.DateTime> _PhotoCreateDate;
		
		private string _SectionCode;
		
		private string _SectionDisplayName;
		
		private string _SectionFriendlyUrl;
		
		public viewAdvertismentPhoto()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string text
		{
			get
			{
				return this._text;
			}
			set
			{
				if ((this._text != value))
				{
					this._text = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime NOT NULL")]
		public System.DateTime createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this._createDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this._link = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteName", DbType="VarChar(100)")]
		public string siteName
		{
			get
			{
				return this._siteName;
			}
			set
			{
				if ((this._siteName != value))
				{
					this._siteName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subpurchaseAdvertisment", DbType="Bit NOT NULL")]
		public bool subpurchaseAdvertisment
		{
			get
			{
				return this._subpurchaseAdvertisment;
			}
			set
			{
				if ((this._subpurchaseAdvertisment != value))
				{
					this._subpurchaseAdvertisment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubPurchase_Id", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> SubPurchase_Id
		{
			get
			{
				return this._SubPurchase_Id;
			}
			set
			{
				if ((this._SubPurchase_Id != value))
				{
					this._SubPurchase_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhotoId", DbType="Int NOT NULL")]
		public int PhotoId
		{
			get
			{
				return this._PhotoId;
			}
			set
			{
				if ((this._PhotoId != value))
				{
					this._PhotoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhotoFileName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string PhotoFileName
		{
			get
			{
				return this._PhotoFileName;
			}
			set
			{
				if ((this._PhotoFileName != value))
				{
					this._PhotoFileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhotoCreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PhotoCreateDate
		{
			get
			{
				return this._PhotoCreateDate;
			}
			set
			{
				if ((this._PhotoCreateDate != value))
				{
					this._PhotoCreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SectionCode", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string SectionCode
		{
			get
			{
				return this._SectionCode;
			}
			set
			{
				if ((this._SectionCode != value))
				{
					this._SectionCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SectionDisplayName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string SectionDisplayName
		{
			get
			{
				return this._SectionDisplayName;
			}
			set
			{
				if ((this._SectionDisplayName != value))
				{
					this._SectionDisplayName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SectionFriendlyUrl", DbType="VarChar(MAX)")]
		public string SectionFriendlyUrl
		{
			get
			{
				return this._SectionFriendlyUrl;
			}
			set
			{
				if ((this._SectionFriendlyUrl != value))
				{
					this._SectionFriendlyUrl = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AdvertismentPhones")]
	public partial class AdvertismentPhone : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _phone;
		
		private int _AdvertismentId;
		
		private EntityRef<viewAdvertisment> _viewAdvertisment;
		
		private EntityRef<Advertisment> _Advertisment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnAdvertismentIdChanging(int value);
    partial void OnAdvertismentIdChanged();
    #endregion
		
		public AdvertismentPhone()
		{
			this._viewAdvertisment = default(EntityRef<viewAdvertisment>);
			this._Advertisment = default(EntityRef<Advertisment>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(80)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvertismentId", DbType="Int NOT NULL")]
		public int AdvertismentId
		{
			get
			{
				return this._AdvertismentId;
			}
			set
			{
				if ((this._AdvertismentId != value))
				{
					if ((this._viewAdvertisment.HasLoadedOrAssignedValue || this._Advertisment.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAdvertismentIdChanging(value);
					this.SendPropertyChanging();
					this._AdvertismentId = value;
					this.SendPropertyChanged("AdvertismentId");
					this.OnAdvertismentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="viewAdvertisment_AdvertismentPhone", Storage="_viewAdvertisment", ThisKey="AdvertismentId", OtherKey="Id", IsForeignKey=true)]
		public viewAdvertisment viewAdvertisment
		{
			get
			{
				return this._viewAdvertisment.Entity;
			}
			set
			{
				viewAdvertisment previousValue = this._viewAdvertisment.Entity;
				if (((previousValue != value) 
							|| (this._viewAdvertisment.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._viewAdvertisment.Entity = null;
						previousValue.AdvertismentPhones.Remove(this);
					}
					this._viewAdvertisment.Entity = value;
					if ((value != null))
					{
						value.AdvertismentPhones.Add(this);
						this._AdvertismentId = value.Id;
					}
					else
					{
						this._AdvertismentId = default(int);
					}
					this.SendPropertyChanged("viewAdvertisment");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Advertisment_AdvertismentPhone", Storage="_Advertisment", ThisKey="AdvertismentId", OtherKey="Id", IsForeignKey=true)]
		public Advertisment Advertisment
		{
			get
			{
				return this._Advertisment.Entity;
			}
			set
			{
				Advertisment previousValue = this._Advertisment.Entity;
				if (((previousValue != value) 
							|| (this._Advertisment.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Advertisment.Entity = null;
						previousValue.AdvertismentPhones.Remove(this);
					}
					this._Advertisment.Entity = value;
					if ((value != null))
					{
						value.AdvertismentPhones.Add(this);
						this._AdvertismentId = value.Id;
					}
					else
					{
						this._AdvertismentId = default(int);
					}
					this.SendPropertyChanged("Advertisment");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WebSearchFilterAdvertisments")]
	public partial class WebSearchFilterAdvertisment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _text;
		
		private string _title;
		
		private System.DateTime _createDate;
		
		private string _subPurchasePhone;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OntextChanging(string value);
    partial void OntextChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OncreateDateChanging(System.DateTime value);
    partial void OncreateDateChanged();
    partial void OnsubPurchasePhoneChanging(string value);
    partial void OnsubPurchasePhoneChanged();
    #endregion
		
		public WebSearchFilterAdvertisment()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text", DbType="NVarChar(MAX)")]
		public string text
		{
			get
			{
				return this._text;
			}
			set
			{
				if ((this._text != value))
				{
					this.OntextChanging(value);
					this.SendPropertyChanging();
					this._text = value;
					this.SendPropertyChanged("text");
					this.OntextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(MAX)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime NOT NULL")]
		public System.DateTime createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subPurchasePhone", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string subPurchasePhone
		{
			get
			{
				return this._subPurchasePhone;
			}
			set
			{
				if ((this._subPurchasePhone != value))
				{
					this.OnsubPurchasePhoneChanging(value);
					this.SendPropertyChanging();
					this._subPurchasePhone = value;
					this.SendPropertyChanged("subPurchasePhone");
					this.OnsubPurchasePhoneChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.viewAdvertisments")]
	public partial class viewAdvertisment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _text;
		
		private System.DateTime _createDate;
		
		private System.DateTime _modifyDate;
		
		private System.Nullable<int> _searchresult_id;
		
		private int _AdvertismentSection_Id;
		
		private string _link;
		
		private string _siteName;
		
		private bool _subpurchaseAdvertisment;
		
		private System.Nullable<System.Guid> _SubPurchase_Id;
		
		private bool _not_realestate;
		
		private bool _not_show_advertisment;
		
		private bool _isSpecial;
		
		private System.Nullable<System.DateTime> _isSpecialDateTime;
		
		private System.Nullable<int> _AdvertismentSubSection_Id;
		
		private System.Nullable<int> _UserID;
		
		private string _Address1;
		
		private int _CountByTextColumn = default(int);
		
		private EntitySet<AdvertismentPhone> _AdvertismentPhones;
		
		private EntitySet<AdvertismentsPhoto> _AdvertismentsPhotos;
		
		private EntityRef<SearchResult> _SearchResult;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OntextChanging(string value);
    partial void OntextChanged();
    partial void OncreateDateChanging(System.DateTime value);
    partial void OncreateDateChanged();
    partial void OnmodifyDateChanging(System.DateTime value);
    partial void OnmodifyDateChanged();
    partial void Onsearchresult_idChanging(System.Nullable<int> value);
    partial void Onsearchresult_idChanged();
    partial void OnAdvertismentSection_IdChanging(int value);
    partial void OnAdvertismentSection_IdChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    partial void OnsiteNameChanging(string value);
    partial void OnsiteNameChanged();
    partial void OnsubpurchaseAdvertismentChanging(bool value);
    partial void OnsubpurchaseAdvertismentChanged();
    partial void OnSubPurchase_IdChanging(System.Nullable<System.Guid> value);
    partial void OnSubPurchase_IdChanged();
    partial void Onnot_realestateChanging(bool value);
    partial void Onnot_realestateChanged();
    partial void Onnot_show_advertismentChanging(bool value);
    partial void Onnot_show_advertismentChanged();
    partial void OnisSpecialChanging(bool value);
    partial void OnisSpecialChanged();
    partial void OnisSpecialDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnisSpecialDateTimeChanged();
    partial void OnAdvertismentSubSection_IdChanging(System.Nullable<int> value);
    partial void OnAdvertismentSubSection_IdChanged();
    partial void OnUserIDChanging(System.Nullable<int> value);
    partial void OnUserIDChanged();
    partial void OnAddress1Changing(string value);
    partial void OnAddress1Changed();
    #endregion
		
		public viewAdvertisment()
		{
			this._AdvertismentPhones = new EntitySet<AdvertismentPhone>(new Action<AdvertismentPhone>(this.attach_AdvertismentPhones), new Action<AdvertismentPhone>(this.detach_AdvertismentPhones));
			this._AdvertismentsPhotos = new EntitySet<AdvertismentsPhoto>(new Action<AdvertismentsPhoto>(this.attach_AdvertismentsPhotos), new Action<AdvertismentsPhoto>(this.detach_AdvertismentsPhotos));
			this._SearchResult = default(EntityRef<SearchResult>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string text
		{
			get
			{
				return this._text;
			}
			set
			{
				if ((this._text != value))
				{
					this.OntextChanging(value);
					this.SendPropertyChanging();
					this._text = value;
					this.SendPropertyChanged("text");
					this.OntextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime NOT NULL")]
		public System.DateTime createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modifyDate", DbType="DateTime NOT NULL")]
		public System.DateTime modifyDate
		{
			get
			{
				return this._modifyDate;
			}
			set
			{
				if ((this._modifyDate != value))
				{
					this.OnmodifyDateChanging(value);
					this.SendPropertyChanging();
					this._modifyDate = value;
					this.SendPropertyChanged("modifyDate");
					this.OnmodifyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchresult_id", DbType="Int")]
		public System.Nullable<int> searchresult_id
		{
			get
			{
				return this._searchresult_id;
			}
			set
			{
				if ((this._searchresult_id != value))
				{
					if (this._SearchResult.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsearchresult_idChanging(value);
					this.SendPropertyChanging();
					this._searchresult_id = value;
					this.SendPropertyChanged("searchresult_id");
					this.Onsearchresult_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvertismentSection_Id", DbType="Int NOT NULL")]
		public int AdvertismentSection_Id
		{
			get
			{
				return this._AdvertismentSection_Id;
			}
			set
			{
				if ((this._AdvertismentSection_Id != value))
				{
					this.OnAdvertismentSection_IdChanging(value);
					this.SendPropertyChanging();
					this._AdvertismentSection_Id = value;
					this.SendPropertyChanged("AdvertismentSection_Id");
					this.OnAdvertismentSection_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this.OnlinkChanging(value);
					this.SendPropertyChanging();
					this._link = value;
					this.SendPropertyChanged("link");
					this.OnlinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteName", DbType="VarChar(MAX)")]
		public string siteName
		{
			get
			{
				return this._siteName;
			}
			set
			{
				if ((this._siteName != value))
				{
					this.OnsiteNameChanging(value);
					this.SendPropertyChanging();
					this._siteName = value;
					this.SendPropertyChanged("siteName");
					this.OnsiteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subpurchaseAdvertisment", DbType="Bit NOT NULL")]
		public bool subpurchaseAdvertisment
		{
			get
			{
				return this._subpurchaseAdvertisment;
			}
			set
			{
				if ((this._subpurchaseAdvertisment != value))
				{
					this.OnsubpurchaseAdvertismentChanging(value);
					this.SendPropertyChanging();
					this._subpurchaseAdvertisment = value;
					this.SendPropertyChanged("subpurchaseAdvertisment");
					this.OnsubpurchaseAdvertismentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubPurchase_Id", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> SubPurchase_Id
		{
			get
			{
				return this._SubPurchase_Id;
			}
			set
			{
				if ((this._SubPurchase_Id != value))
				{
					this.OnSubPurchase_IdChanging(value);
					this.SendPropertyChanging();
					this._SubPurchase_Id = value;
					this.SendPropertyChanged("SubPurchase_Id");
					this.OnSubPurchase_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_not_realestate", DbType="Bit NOT NULL")]
		public bool not_realestate
		{
			get
			{
				return this._not_realestate;
			}
			set
			{
				if ((this._not_realestate != value))
				{
					this.Onnot_realestateChanging(value);
					this.SendPropertyChanging();
					this._not_realestate = value;
					this.SendPropertyChanged("not_realestate");
					this.Onnot_realestateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_not_show_advertisment", DbType="Bit NOT NULL")]
		public bool not_show_advertisment
		{
			get
			{
				return this._not_show_advertisment;
			}
			set
			{
				if ((this._not_show_advertisment != value))
				{
					this.Onnot_show_advertismentChanging(value);
					this.SendPropertyChanging();
					this._not_show_advertisment = value;
					this.SendPropertyChanged("not_show_advertisment");
					this.Onnot_show_advertismentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isSpecial", DbType="Bit NOT NULL")]
		public bool isSpecial
		{
			get
			{
				return this._isSpecial;
			}
			set
			{
				if ((this._isSpecial != value))
				{
					this.OnisSpecialChanging(value);
					this.SendPropertyChanging();
					this._isSpecial = value;
					this.SendPropertyChanged("isSpecial");
					this.OnisSpecialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isSpecialDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> isSpecialDateTime
		{
			get
			{
				return this._isSpecialDateTime;
			}
			set
			{
				if ((this._isSpecialDateTime != value))
				{
					this.OnisSpecialDateTimeChanging(value);
					this.SendPropertyChanging();
					this._isSpecialDateTime = value;
					this.SendPropertyChanged("isSpecialDateTime");
					this.OnisSpecialDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvertismentSubSection_Id", DbType="Int")]
		public System.Nullable<int> AdvertismentSubSection_Id
		{
			get
			{
				return this._AdvertismentSubSection_Id;
			}
			set
			{
				if ((this._AdvertismentSubSection_Id != value))
				{
					this.OnAdvertismentSubSection_IdChanging(value);
					this.SendPropertyChanging();
					this._AdvertismentSubSection_Id = value;
					this.SendPropertyChanged("AdvertismentSubSection_Id");
					this.OnAdvertismentSubSection_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1")]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this.OnAddress1Changing(value);
					this.SendPropertyChanging();
					this._Address1 = value;
					this.SendPropertyChanged("Address1");
					this.OnAddress1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountByTextColumn", UpdateCheck=UpdateCheck.Never)]
		public int CountByTextColumn
		{
			get
			{
				return this._CountByTextColumn;
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="viewAdvertisment_AdvertismentPhone", Storage="_AdvertismentPhones", ThisKey="Id", OtherKey="AdvertismentId")]
		public EntitySet<AdvertismentPhone> AdvertismentPhones
		{
			get
			{
				return this._AdvertismentPhones;
			}
			set
			{
				this._AdvertismentPhones.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="viewAdvertisment_AdvertismentsPhoto", Storage="_AdvertismentsPhotos", ThisKey="Id", OtherKey="Advertisment_Id")]
		public EntitySet<AdvertismentsPhoto> AdvertismentsPhotos
		{
			get
			{
				return this._AdvertismentsPhotos;
			}
			set
			{
				this._AdvertismentsPhotos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SearchResult_viewAdvertisment", Storage="_SearchResult", ThisKey="searchresult_id", OtherKey="Id", IsForeignKey=true)]
		public SearchResult SearchResult
		{
			get
			{
				return this._SearchResult.Entity;
			}
			set
			{
				SearchResult previousValue = this._SearchResult.Entity;
				if (((previousValue != value) 
							|| (this._SearchResult.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SearchResult.Entity = null;
						previousValue.viewAdvertisments.Remove(this);
					}
					this._SearchResult.Entity = value;
					if ((value != null))
					{
						value.viewAdvertisments.Add(this);
						this._searchresult_id = value.Id;
					}
					else
					{
						this._searchresult_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("SearchResult");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AdvertismentPhones(AdvertismentPhone entity)
		{
			this.SendPropertyChanging();
			entity.viewAdvertisment = this;
		}
		
		private void detach_AdvertismentPhones(AdvertismentPhone entity)
		{
			this.SendPropertyChanging();
			entity.viewAdvertisment = null;
		}
		
		private void attach_AdvertismentsPhotos(AdvertismentsPhoto entity)
		{
			this.SendPropertyChanging();
			entity.viewAdvertisment = this;
		}
		
		private void detach_AdvertismentsPhotos(AdvertismentsPhoto entity)
		{
			this.SendPropertyChanging();
			entity.viewAdvertisment = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AdvertismentSections")]
	public partial class AdvertismentSection : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _code;
		
		private string _displayName;
		
		private string _friendlyUrl;
		
		private string _Title;
		
		private string _Description;
		
		private string _Keywords;
		
		private EntitySet<SearchResult> _SearchResults;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void OndisplayNameChanging(string value);
    partial void OndisplayNameChanged();
    partial void OnfriendlyUrlChanging(string value);
    partial void OnfriendlyUrlChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnKeywordsChanging(string value);
    partial void OnKeywordsChanged();
    #endregion
		
		public AdvertismentSection()
		{
			this._SearchResults = new EntitySet<SearchResult>(new Action<SearchResult>(this.attach_SearchResults), new Action<SearchResult>(this.detach_SearchResults));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_displayName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string displayName
		{
			get
			{
				return this._displayName;
			}
			set
			{
				if ((this._displayName != value))
				{
					this.OndisplayNameChanging(value);
					this.SendPropertyChanging();
					this._displayName = value;
					this.SendPropertyChanged("displayName");
					this.OndisplayNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_friendlyUrl", DbType="VarChar(MAX)")]
		public string friendlyUrl
		{
			get
			{
				return this._friendlyUrl;
			}
			set
			{
				if ((this._friendlyUrl != value))
				{
					this.OnfriendlyUrlChanging(value);
					this.SendPropertyChanging();
					this._friendlyUrl = value;
					this.SendPropertyChanged("friendlyUrl");
					this.OnfriendlyUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keywords")]
		public string Keywords
		{
			get
			{
				return this._Keywords;
			}
			set
			{
				if ((this._Keywords != value))
				{
					this.OnKeywordsChanging(value);
					this.SendPropertyChanging();
					this._Keywords = value;
					this.SendPropertyChanged("Keywords");
					this.OnKeywordsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AdvertismentSection_SearchResult", Storage="_SearchResults", ThisKey="Id", OtherKey="AdvertismentSection_Id")]
		public EntitySet<SearchResult> SearchResults
		{
			get
			{
				return this._SearchResults;
			}
			set
			{
				this._SearchResults.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SearchResults(SearchResult entity)
		{
			this.SendPropertyChanging();
			entity.AdvertismentSection = this;
		}
		
		private void detach_SearchResults(SearchResult entity)
		{
			this.SendPropertyChanging();
			entity.AdvertismentSection = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AdvertismentsPhotoes")]
	public partial class AdvertismentsPhoto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _filename;
		
		private int _Advertisment_Id;
		
		private System.Nullable<System.DateTime> _createDate;
		
		private EntityRef<viewAdvertisment> _viewAdvertisment;
		
		private EntityRef<Advertisment> _Advertisment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnfilenameChanging(string value);
    partial void OnfilenameChanged();
    partial void OnAdvertisment_IdChanging(int value);
    partial void OnAdvertisment_IdChanged();
    partial void OncreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OncreateDateChanged();
    #endregion
		
		public AdvertismentsPhoto()
		{
			this._viewAdvertisment = default(EntityRef<viewAdvertisment>);
			this._Advertisment = default(EntityRef<Advertisment>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filename", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string filename
		{
			get
			{
				return this._filename;
			}
			set
			{
				if ((this._filename != value))
				{
					this.OnfilenameChanging(value);
					this.SendPropertyChanging();
					this._filename = value;
					this.SendPropertyChanged("filename");
					this.OnfilenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advertisment_Id", DbType="Int NOT NULL")]
		public int Advertisment_Id
		{
			get
			{
				return this._Advertisment_Id;
			}
			set
			{
				if ((this._Advertisment_Id != value))
				{
					if ((this._viewAdvertisment.HasLoadedOrAssignedValue || this._Advertisment.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAdvertisment_IdChanging(value);
					this.SendPropertyChanging();
					this._Advertisment_Id = value;
					this.SendPropertyChanged("Advertisment_Id");
					this.OnAdvertisment_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="viewAdvertisment_AdvertismentsPhoto", Storage="_viewAdvertisment", ThisKey="Advertisment_Id", OtherKey="Id", IsForeignKey=true)]
		public viewAdvertisment viewAdvertisment
		{
			get
			{
				return this._viewAdvertisment.Entity;
			}
			set
			{
				viewAdvertisment previousValue = this._viewAdvertisment.Entity;
				if (((previousValue != value) 
							|| (this._viewAdvertisment.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._viewAdvertisment.Entity = null;
						previousValue.AdvertismentsPhotos.Remove(this);
					}
					this._viewAdvertisment.Entity = value;
					if ((value != null))
					{
						value.AdvertismentsPhotos.Add(this);
						this._Advertisment_Id = value.Id;
					}
					else
					{
						this._Advertisment_Id = default(int);
					}
					this.SendPropertyChanged("viewAdvertisment");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Advertisment_AdvertismentsPhoto", Storage="_Advertisment", ThisKey="Advertisment_Id", OtherKey="Id", IsForeignKey=true)]
		public Advertisment Advertisment
		{
			get
			{
				return this._Advertisment.Entity;
			}
			set
			{
				Advertisment previousValue = this._Advertisment.Entity;
				if (((previousValue != value) 
							|| (this._Advertisment.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Advertisment.Entity = null;
						previousValue.AdvertismentsPhotos.Remove(this);
					}
					this._Advertisment.Entity = value;
					if ((value != null))
					{
						value.AdvertismentsPhotos.Add(this);
						this._Advertisment_Id = value.Id;
					}
					else
					{
						this._Advertisment_Id = default(int);
					}
					this.SendPropertyChanged("Advertisment");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AdvertismentSubSection")]
	public partial class AdvertismentSubSection
	{
		
		private int _Id;
		
		private string _code;
		
		private string _displayName;
		
		private string _friendlyUrl;
		
		private int _AdvertismentSection_Id;
		
		private string _Title;
		
		private string _Description;
		
		private string _Keywords;
		
		public AdvertismentSubSection()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this._code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_displayName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string displayName
		{
			get
			{
				return this._displayName;
			}
			set
			{
				if ((this._displayName != value))
				{
					this._displayName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_friendlyUrl", DbType="NVarChar(MAX)")]
		public string friendlyUrl
		{
			get
			{
				return this._friendlyUrl;
			}
			set
			{
				if ((this._friendlyUrl != value))
				{
					this._friendlyUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvertismentSection_Id", DbType="Int NOT NULL")]
		public int AdvertismentSection_Id
		{
			get
			{
				return this._AdvertismentSection_Id;
			}
			set
			{
				if ((this._AdvertismentSection_Id != value))
				{
					this._AdvertismentSection_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keywords")]
		public string Keywords
		{
			get
			{
				return this._Keywords;
			}
			set
			{
				if ((this._Keywords != value))
				{
					this._Keywords = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Articles")]
	public partial class Article : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _article_id;
		
		private string _header;
		
		private string _text;
		
		private System.DateTime _createDate;
		
		private string _author;
		
		private string _link;
		
		private string _description;
		
		private string _keywords;
		
		private string _title;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onarticle_idChanging(System.Guid value);
    partial void Onarticle_idChanged();
    partial void OnheaderChanging(string value);
    partial void OnheaderChanged();
    partial void OntextChanging(string value);
    partial void OntextChanged();
    partial void OncreateDateChanging(System.DateTime value);
    partial void OncreateDateChanged();
    partial void OnauthorChanging(string value);
    partial void OnauthorChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnkeywordsChanging(string value);
    partial void OnkeywordsChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    #endregion
		
		public Article()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_article_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid article_id
		{
			get
			{
				return this._article_id;
			}
			set
			{
				if ((this._article_id != value))
				{
					this.Onarticle_idChanging(value);
					this.SendPropertyChanging();
					this._article_id = value;
					this.SendPropertyChanged("article_id");
					this.Onarticle_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_header", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string header
		{
			get
			{
				return this._header;
			}
			set
			{
				if ((this._header != value))
				{
					this.OnheaderChanging(value);
					this.SendPropertyChanging();
					this._header = value;
					this.SendPropertyChanged("header");
					this.OnheaderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string text
		{
			get
			{
				return this._text;
			}
			set
			{
				if ((this._text != value))
				{
					this.OntextChanging(value);
					this.SendPropertyChanging();
					this._text = value;
					this.SendPropertyChanged("text");
					this.OntextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime NOT NULL")]
		public System.DateTime createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_author", DbType="VarChar(40)")]
		public string author
		{
			get
			{
				return this._author;
			}
			set
			{
				if ((this._author != value))
				{
					this.OnauthorChanging(value);
					this.SendPropertyChanging();
					this._author = value;
					this.SendPropertyChanged("author");
					this.OnauthorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this.OnlinkChanging(value);
					this.SendPropertyChanging();
					this._link = value;
					this.SendPropertyChanged("link");
					this.OnlinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_keywords", DbType="VarChar(MAX)")]
		public string keywords
		{
			get
			{
				return this._keywords;
			}
			set
			{
				if ((this._keywords != value))
				{
					this.OnkeywordsChanging(value);
					this.SendPropertyChanging();
					this._keywords = value;
					this.SendPropertyChanged("keywords");
					this.OnkeywordsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SearchResults")]
	public partial class SearchResult : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.DateTime _createDate;
		
		private int _allParsedAdvertismentsCount;
		
		private int _AdvertismentSection_Id;
		
		private System.DateTime _modifyDate;
		
		private EntitySet<Advertisment> _Advertisments;
		
		private EntitySet<viewAdvertisment> _viewAdvertisments;
		
		private EntityRef<AdvertismentSection> _AdvertismentSection;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OncreateDateChanging(System.DateTime value);
    partial void OncreateDateChanged();
    partial void OnallParsedAdvertismentsCountChanging(int value);
    partial void OnallParsedAdvertismentsCountChanged();
    partial void OnAdvertismentSection_IdChanging(int value);
    partial void OnAdvertismentSection_IdChanged();
    partial void OnmodifyDateChanging(System.DateTime value);
    partial void OnmodifyDateChanged();
    #endregion
		
		public SearchResult()
		{
			this._Advertisments = new EntitySet<Advertisment>(new Action<Advertisment>(this.attach_Advertisments), new Action<Advertisment>(this.detach_Advertisments));
			this._viewAdvertisments = new EntitySet<viewAdvertisment>(new Action<viewAdvertisment>(this.attach_viewAdvertisments), new Action<viewAdvertisment>(this.detach_viewAdvertisments));
			this._AdvertismentSection = default(EntityRef<AdvertismentSection>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime NOT NULL")]
		public System.DateTime createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_allParsedAdvertismentsCount", DbType="Int NOT NULL")]
		public int allParsedAdvertismentsCount
		{
			get
			{
				return this._allParsedAdvertismentsCount;
			}
			set
			{
				if ((this._allParsedAdvertismentsCount != value))
				{
					this.OnallParsedAdvertismentsCountChanging(value);
					this.SendPropertyChanging();
					this._allParsedAdvertismentsCount = value;
					this.SendPropertyChanged("allParsedAdvertismentsCount");
					this.OnallParsedAdvertismentsCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvertismentSection_Id", DbType="Int NOT NULL")]
		public int AdvertismentSection_Id
		{
			get
			{
				return this._AdvertismentSection_Id;
			}
			set
			{
				if ((this._AdvertismentSection_Id != value))
				{
					if (this._AdvertismentSection.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAdvertismentSection_IdChanging(value);
					this.SendPropertyChanging();
					this._AdvertismentSection_Id = value;
					this.SendPropertyChanged("AdvertismentSection_Id");
					this.OnAdvertismentSection_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modifyDate", DbType="DateTime NOT NULL")]
		public System.DateTime modifyDate
		{
			get
			{
				return this._modifyDate;
			}
			set
			{
				if ((this._modifyDate != value))
				{
					this.OnmodifyDateChanging(value);
					this.SendPropertyChanging();
					this._modifyDate = value;
					this.SendPropertyChanged("modifyDate");
					this.OnmodifyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SearchResult_Advertisment", Storage="_Advertisments", ThisKey="Id", OtherKey="searchresult_id")]
		public EntitySet<Advertisment> Advertisments
		{
			get
			{
				return this._Advertisments;
			}
			set
			{
				this._Advertisments.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SearchResult_viewAdvertisment", Storage="_viewAdvertisments", ThisKey="Id", OtherKey="searchresult_id")]
		public EntitySet<viewAdvertisment> viewAdvertisments
		{
			get
			{
				return this._viewAdvertisments;
			}
			set
			{
				this._viewAdvertisments.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AdvertismentSection_SearchResult", Storage="_AdvertismentSection", ThisKey="AdvertismentSection_Id", OtherKey="Id", IsForeignKey=true)]
		public AdvertismentSection AdvertismentSection
		{
			get
			{
				return this._AdvertismentSection.Entity;
			}
			set
			{
				AdvertismentSection previousValue = this._AdvertismentSection.Entity;
				if (((previousValue != value) 
							|| (this._AdvertismentSection.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AdvertismentSection.Entity = null;
						previousValue.SearchResults.Remove(this);
					}
					this._AdvertismentSection.Entity = value;
					if ((value != null))
					{
						value.SearchResults.Add(this);
						this._AdvertismentSection_Id = value.Id;
					}
					else
					{
						this._AdvertismentSection_Id = default(int);
					}
					this.SendPropertyChanged("AdvertismentSection");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Advertisments(Advertisment entity)
		{
			this.SendPropertyChanging();
			entity.SearchResult = this;
		}
		
		private void detach_Advertisments(Advertisment entity)
		{
			this.SendPropertyChanging();
			entity.SearchResult = null;
		}
		
		private void attach_viewAdvertisments(viewAdvertisment entity)
		{
			this.SendPropertyChanging();
			entity.SearchResult = this;
		}
		
		private void detach_viewAdvertisments(viewAdvertisment entity)
		{
			this.SendPropertyChanging();
			entity.SearchResult = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SubPurchasePhones")]
	public partial class SubPurchasePhone : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _phone;
		
		private System.Guid _SubPurchaseId;
		
		private System.DateTime _createDate;
		
		private EntityRef<SubPurchase> _SubPurchase;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnSubPurchaseIdChanging(System.Guid value);
    partial void OnSubPurchaseIdChanged();
    partial void OncreateDateChanging(System.DateTime value);
    partial void OncreateDateChanged();
    #endregion
		
		public SubPurchasePhone()
		{
			this._SubPurchase = default(EntityRef<SubPurchase>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubPurchaseId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid SubPurchaseId
		{
			get
			{
				return this._SubPurchaseId;
			}
			set
			{
				if ((this._SubPurchaseId != value))
				{
					if (this._SubPurchase.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSubPurchaseIdChanging(value);
					this.SendPropertyChanging();
					this._SubPurchaseId = value;
					this.SendPropertyChanged("SubPurchaseId");
					this.OnSubPurchaseIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime NOT NULL")]
		public System.DateTime createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SubPurchase_SubPurchasePhone", Storage="_SubPurchase", ThisKey="SubPurchaseId", OtherKey="id", IsForeignKey=true)]
		public SubPurchase SubPurchase
		{
			get
			{
				return this._SubPurchase.Entity;
			}
			set
			{
				SubPurchase previousValue = this._SubPurchase.Entity;
				if (((previousValue != value) 
							|| (this._SubPurchase.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SubPurchase.Entity = null;
						previousValue.SubPurchasePhones.Remove(this);
					}
					this._SubPurchase.Entity = value;
					if ((value != null))
					{
						value.SubPurchasePhones.Add(this);
						this._SubPurchaseId = value.id;
					}
					else
					{
						this._SubPurchaseId = default(System.Guid);
					}
					this.SendPropertyChanged("SubPurchase");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SubPurchases")]
	public partial class SubPurchase : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private string _phone;
		
		private string _name;
		
		private string _surname;
		
		private System.Nullable<bool> _not_checked;
		
		private System.Nullable<System.DateTime> _createDate;
		
		private System.Nullable<int> _Advertisment_Id;
		
		private System.Nullable<System.DateTime> _modifyDate;
		
		private EntitySet<SubPurchasePhone> _SubPurchasePhones;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnsurnameChanging(string value);
    partial void OnsurnameChanged();
    partial void Onnot_checkedChanging(System.Nullable<bool> value);
    partial void Onnot_checkedChanged();
    partial void OncreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OncreateDateChanged();
    partial void OnAdvertisment_IdChanging(System.Nullable<int> value);
    partial void OnAdvertisment_IdChanged();
    partial void OnmodifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnmodifyDateChanged();
    #endregion
		
		public SubPurchase()
		{
			this._SubPurchasePhones = new EntitySet<SubPurchasePhone>(new Action<SubPurchasePhone>(this.attach_SubPurchasePhones), new Action<SubPurchasePhone>(this.detach_SubPurchasePhones));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(20)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(30)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_surname", DbType="VarChar(30)")]
		public string surname
		{
			get
			{
				return this._surname;
			}
			set
			{
				if ((this._surname != value))
				{
					this.OnsurnameChanging(value);
					this.SendPropertyChanging();
					this._surname = value;
					this.SendPropertyChanged("surname");
					this.OnsurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_not_checked", DbType="Bit")]
		public System.Nullable<bool> not_checked
		{
			get
			{
				return this._not_checked;
			}
			set
			{
				if ((this._not_checked != value))
				{
					this.Onnot_checkedChanging(value);
					this.SendPropertyChanging();
					this._not_checked = value;
					this.SendPropertyChanged("not_checked");
					this.Onnot_checkedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advertisment_Id", DbType="Int")]
		public System.Nullable<int> Advertisment_Id
		{
			get
			{
				return this._Advertisment_Id;
			}
			set
			{
				if ((this._Advertisment_Id != value))
				{
					this.OnAdvertisment_IdChanging(value);
					this.SendPropertyChanging();
					this._Advertisment_Id = value;
					this.SendPropertyChanged("Advertisment_Id");
					this.OnAdvertisment_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> modifyDate
		{
			get
			{
				return this._modifyDate;
			}
			set
			{
				if ((this._modifyDate != value))
				{
					this.OnmodifyDateChanging(value);
					this.SendPropertyChanging();
					this._modifyDate = value;
					this.SendPropertyChanged("modifyDate");
					this.OnmodifyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SubPurchase_SubPurchasePhone", Storage="_SubPurchasePhones", ThisKey="id", OtherKey="SubPurchaseId")]
		public EntitySet<SubPurchasePhone> SubPurchasePhones
		{
			get
			{
				return this._SubPurchasePhones;
			}
			set
			{
				this._SubPurchasePhones.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SubPurchasePhones(SubPurchasePhone entity)
		{
			this.SendPropertyChanging();
			entity.SubPurchase = this;
		}
		
		private void detach_SubPurchasePhones(SubPurchasePhone entity)
		{
			this.SendPropertyChanging();
			entity.SubPurchase = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserID;
		
		private string _Password;
		
		private string _Email;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _VkontakteID;
		
		private bool _IsSubPurchase;
		
		private System.Nullable<System.Guid> _SubPurchaseID;
		
		private string _Login;
		
		private bool _IsAdmin;
		
		private string _Phone;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnVkontakteIDChanging(string value);
    partial void OnVkontakteIDChanged();
    partial void OnIsSubPurchaseChanging(bool value);
    partial void OnIsSubPurchaseChanged();
    partial void OnSubPurchaseIDChanging(System.Nullable<System.Guid> value);
    partial void OnSubPurchaseIDChanged();
    partial void OnLoginChanging(string value);
    partial void OnLoginChanged();
    partial void OnIsAdminChanging(bool value);
    partial void OnIsAdminChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(MAX)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(40)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(40)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VkontakteID", DbType="VarChar(20)")]
		public string VkontakteID
		{
			get
			{
				return this._VkontakteID;
			}
			set
			{
				if ((this._VkontakteID != value))
				{
					this.OnVkontakteIDChanging(value);
					this.SendPropertyChanging();
					this._VkontakteID = value;
					this.SendPropertyChanged("VkontakteID");
					this.OnVkontakteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSubPurchase", DbType="Bit NOT NULL")]
		public bool IsSubPurchase
		{
			get
			{
				return this._IsSubPurchase;
			}
			set
			{
				if ((this._IsSubPurchase != value))
				{
					this.OnIsSubPurchaseChanging(value);
					this.SendPropertyChanging();
					this._IsSubPurchase = value;
					this.SendPropertyChanged("IsSubPurchase");
					this.OnIsSubPurchaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubPurchaseID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> SubPurchaseID
		{
			get
			{
				return this._SubPurchaseID;
			}
			set
			{
				if ((this._SubPurchaseID != value))
				{
					this.OnSubPurchaseIDChanging(value);
					this.SendPropertyChanging();
					this._SubPurchaseID = value;
					this.SendPropertyChanged("SubPurchaseID");
					this.OnSubPurchaseIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login", DbType="VarChar(30)")]
		public string Login
		{
			get
			{
				return this._Login;
			}
			set
			{
				if ((this._Login != value))
				{
					this.OnLoginChanging(value);
					this.SendPropertyChanging();
					this._Login = value;
					this.SendPropertyChanged("Login");
					this.OnLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAdmin", DbType="Bit NOT NULL")]
		public bool IsAdmin
		{
			get
			{
				return this._IsAdmin;
			}
			set
			{
				if ((this._IsAdmin != value))
				{
					this.OnIsAdminChanging(value);
					this.SendPropertyChanging();
					this._IsAdmin = value;
					this.SendPropertyChanged("IsAdmin");
					this.OnIsAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(20)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Advertisments")]
	public partial class Advertisment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _text;
		
		private System.DateTime _createDate;
		
		private System.DateTime _modifyDate;
		
		private System.Nullable<int> _searchresult_id;
		
		private int _AdvertismentSection_Id;
		
		private string _link;
		
		private string _siteName;
		
		private bool _subpurchaseAdvertisment;
		
		private System.Nullable<System.Guid> _SubPurchase_Id;
		
		private bool _not_realestate;
		
		private bool _not_show_advertisment;
		
		private bool _isSpecial;
		
		private System.Nullable<System.DateTime> _isSpecialDateTime;
		
		private System.Nullable<int> _AdvertismentSubSection_Id;
		
		private System.Nullable<int> _UserID;
		
		private string _Address1;
		
		private EntitySet<AdvertismentPhone> _AdvertismentPhones;
		
		private EntitySet<AdvertismentsPhoto> _AdvertismentsPhotos;
		
		private EntityRef<SearchResult> _SearchResult;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OntextChanging(string value);
    partial void OntextChanged();
    partial void OncreateDateChanging(System.DateTime value);
    partial void OncreateDateChanged();
    partial void OnmodifyDateChanging(System.DateTime value);
    partial void OnmodifyDateChanged();
    partial void Onsearchresult_idChanging(System.Nullable<int> value);
    partial void Onsearchresult_idChanged();
    partial void OnAdvertismentSection_IdChanging(int value);
    partial void OnAdvertismentSection_IdChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    partial void OnsiteNameChanging(string value);
    partial void OnsiteNameChanged();
    partial void OnsubpurchaseAdvertismentChanging(bool value);
    partial void OnsubpurchaseAdvertismentChanged();
    partial void OnSubPurchase_IdChanging(System.Nullable<System.Guid> value);
    partial void OnSubPurchase_IdChanged();
    partial void Onnot_realestateChanging(bool value);
    partial void Onnot_realestateChanged();
    partial void Onnot_show_advertismentChanging(bool value);
    partial void Onnot_show_advertismentChanged();
    partial void OnisSpecialChanging(bool value);
    partial void OnisSpecialChanged();
    partial void OnisSpecialDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnisSpecialDateTimeChanged();
    partial void OnAdvertismentSubSection_IdChanging(System.Nullable<int> value);
    partial void OnAdvertismentSubSection_IdChanged();
    partial void OnUserIDChanging(System.Nullable<int> value);
    partial void OnUserIDChanged();
    partial void OnAddress1Changing(string value);
    partial void OnAddress1Changed();
    #endregion
		
		public Advertisment()
		{
			this._AdvertismentPhones = new EntitySet<AdvertismentPhone>(new Action<AdvertismentPhone>(this.attach_AdvertismentPhones), new Action<AdvertismentPhone>(this.detach_AdvertismentPhones));
			this._AdvertismentsPhotos = new EntitySet<AdvertismentsPhoto>(new Action<AdvertismentsPhoto>(this.attach_AdvertismentsPhotos), new Action<AdvertismentsPhoto>(this.detach_AdvertismentsPhotos));
			this._SearchResult = default(EntityRef<SearchResult>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string text
		{
			get
			{
				return this._text;
			}
			set
			{
				if ((this._text != value))
				{
					this.OntextChanging(value);
					this.SendPropertyChanging();
					this._text = value;
					this.SendPropertyChanged("text");
					this.OntextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime NOT NULL")]
		public System.DateTime createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modifyDate", DbType="DateTime NOT NULL")]
		public System.DateTime modifyDate
		{
			get
			{
				return this._modifyDate;
			}
			set
			{
				if ((this._modifyDate != value))
				{
					this.OnmodifyDateChanging(value);
					this.SendPropertyChanging();
					this._modifyDate = value;
					this.SendPropertyChanged("modifyDate");
					this.OnmodifyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchresult_id", DbType="Int")]
		public System.Nullable<int> searchresult_id
		{
			get
			{
				return this._searchresult_id;
			}
			set
			{
				if ((this._searchresult_id != value))
				{
					if (this._SearchResult.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsearchresult_idChanging(value);
					this.SendPropertyChanging();
					this._searchresult_id = value;
					this.SendPropertyChanged("searchresult_id");
					this.Onsearchresult_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvertismentSection_Id", DbType="Int NOT NULL")]
		public int AdvertismentSection_Id
		{
			get
			{
				return this._AdvertismentSection_Id;
			}
			set
			{
				if ((this._AdvertismentSection_Id != value))
				{
					this.OnAdvertismentSection_IdChanging(value);
					this.SendPropertyChanging();
					this._AdvertismentSection_Id = value;
					this.SendPropertyChanged("AdvertismentSection_Id");
					this.OnAdvertismentSection_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this.OnlinkChanging(value);
					this.SendPropertyChanging();
					this._link = value;
					this.SendPropertyChanged("link");
					this.OnlinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteName", DbType="VarChar(MAX)")]
		public string siteName
		{
			get
			{
				return this._siteName;
			}
			set
			{
				if ((this._siteName != value))
				{
					this.OnsiteNameChanging(value);
					this.SendPropertyChanging();
					this._siteName = value;
					this.SendPropertyChanged("siteName");
					this.OnsiteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subpurchaseAdvertisment", DbType="Bit NOT NULL")]
		public bool subpurchaseAdvertisment
		{
			get
			{
				return this._subpurchaseAdvertisment;
			}
			set
			{
				if ((this._subpurchaseAdvertisment != value))
				{
					this.OnsubpurchaseAdvertismentChanging(value);
					this.SendPropertyChanging();
					this._subpurchaseAdvertisment = value;
					this.SendPropertyChanged("subpurchaseAdvertisment");
					this.OnsubpurchaseAdvertismentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubPurchase_Id", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> SubPurchase_Id
		{
			get
			{
				return this._SubPurchase_Id;
			}
			set
			{
				if ((this._SubPurchase_Id != value))
				{
					this.OnSubPurchase_IdChanging(value);
					this.SendPropertyChanging();
					this._SubPurchase_Id = value;
					this.SendPropertyChanged("SubPurchase_Id");
					this.OnSubPurchase_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_not_realestate", DbType="Bit NOT NULL")]
		public bool not_realestate
		{
			get
			{
				return this._not_realestate;
			}
			set
			{
				if ((this._not_realestate != value))
				{
					this.Onnot_realestateChanging(value);
					this.SendPropertyChanging();
					this._not_realestate = value;
					this.SendPropertyChanged("not_realestate");
					this.Onnot_realestateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_not_show_advertisment", DbType="Bit NOT NULL")]
		public bool not_show_advertisment
		{
			get
			{
				return this._not_show_advertisment;
			}
			set
			{
				if ((this._not_show_advertisment != value))
				{
					this.Onnot_show_advertismentChanging(value);
					this.SendPropertyChanging();
					this._not_show_advertisment = value;
					this.SendPropertyChanged("not_show_advertisment");
					this.Onnot_show_advertismentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isSpecial", DbType="Bit NOT NULL")]
		public bool isSpecial
		{
			get
			{
				return this._isSpecial;
			}
			set
			{
				if ((this._isSpecial != value))
				{
					this.OnisSpecialChanging(value);
					this.SendPropertyChanging();
					this._isSpecial = value;
					this.SendPropertyChanged("isSpecial");
					this.OnisSpecialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isSpecialDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> isSpecialDateTime
		{
			get
			{
				return this._isSpecialDateTime;
			}
			set
			{
				if ((this._isSpecialDateTime != value))
				{
					this.OnisSpecialDateTimeChanging(value);
					this.SendPropertyChanging();
					this._isSpecialDateTime = value;
					this.SendPropertyChanged("isSpecialDateTime");
					this.OnisSpecialDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvertismentSubSection_Id", DbType="Int")]
		public System.Nullable<int> AdvertismentSubSection_Id
		{
			get
			{
				return this._AdvertismentSubSection_Id;
			}
			set
			{
				if ((this._AdvertismentSubSection_Id != value))
				{
					this.OnAdvertismentSubSection_IdChanging(value);
					this.SendPropertyChanging();
					this._AdvertismentSubSection_Id = value;
					this.SendPropertyChanged("AdvertismentSubSection_Id");
					this.OnAdvertismentSubSection_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1")]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this.OnAddress1Changing(value);
					this.SendPropertyChanging();
					this._Address1 = value;
					this.SendPropertyChanged("Address1");
					this.OnAddress1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Advertisment_AdvertismentPhone", Storage="_AdvertismentPhones", ThisKey="Id", OtherKey="AdvertismentId")]
		public EntitySet<AdvertismentPhone> AdvertismentPhones
		{
			get
			{
				return this._AdvertismentPhones;
			}
			set
			{
				this._AdvertismentPhones.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Advertisment_AdvertismentsPhoto", Storage="_AdvertismentsPhotos", ThisKey="Id", OtherKey="Advertisment_Id")]
		public EntitySet<AdvertismentsPhoto> AdvertismentsPhotos
		{
			get
			{
				return this._AdvertismentsPhotos;
			}
			set
			{
				this._AdvertismentsPhotos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SearchResult_Advertisment", Storage="_SearchResult", ThisKey="searchresult_id", OtherKey="Id", IsForeignKey=true)]
		public SearchResult SearchResult
		{
			get
			{
				return this._SearchResult.Entity;
			}
			set
			{
				SearchResult previousValue = this._SearchResult.Entity;
				if (((previousValue != value) 
							|| (this._SearchResult.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SearchResult.Entity = null;
						previousValue.Advertisments.Remove(this);
					}
					this._SearchResult.Entity = value;
					if ((value != null))
					{
						value.Advertisments.Add(this);
						this._searchresult_id = value.Id;
					}
					else
					{
						this._searchresult_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("SearchResult");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AdvertismentPhones(AdvertismentPhone entity)
		{
			this.SendPropertyChanging();
			entity.Advertisment = this;
		}
		
		private void detach_AdvertismentPhones(AdvertismentPhone entity)
		{
			this.SendPropertyChanging();
			entity.Advertisment = null;
		}
		
		private void attach_AdvertismentsPhotos(AdvertismentsPhoto entity)
		{
			this.SendPropertyChanging();
			entity.Advertisment = this;
		}
		
		private void detach_AdvertismentsPhotos(AdvertismentsPhoto entity)
		{
			this.SendPropertyChanging();
			entity.Advertisment = null;
		}
	}
}
#pragma warning restore 1591
